# Generated by Django 4.2 on 2026-06-02 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='exercise',
            new_name='exercises_e_body_pa_5ee11b_idx',
            old_name='exercises_body_part_idx',
        ),
        migrations.RenameIndex(
            model_name='exercise',
            new_name='exercises_e_target_62857b_idx',
            old_name='exercises_target_idx',
        ),
        migrations.RenameIndex(
            model_name='exercise',
            new_name='exercises_e_equipme_ab2632_idx',
            old_name='exercises_equipment_idx',
        ),
    ]
