# Generated by Django 4.2 on 2026-05-28 08:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Clip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('youtube_url', models.URLField()),
                ('video_id', models.CharField(db_index=True, max_length=11, unique=True)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('duration', models.CharField(blank=True, max_length=10)),
                ('subtitles', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='clip',
            index=models.Index(fields=['video_id'], name='clips_clip_video_i_c8c016_idx'),
        ),
        migrations.AddIndex(
            model_name='clip',
            index=models.Index(fields=['user', '-created_at'], name='clips_clip_user_id_c2049e_idx'),
        ),
    ]
