# Generated by Django 4.2 on 2026-05-28 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clips', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clip',
            name='channel',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
