# Generated by Django 4.2 on 2026-05-28 15:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clips', '0002_clip_channel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clip',
            name='video_id',
            field=models.CharField(db_index=True, max_length=11),
        ),
        migrations.AlterUniqueTogether(
            name='clip',
            unique_together={('user', 'video_id')},
        ),
    ]
