# Generated by Django 4.2 on 2026-06-02 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clips', '0005_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='workout_count',
            field=models.IntegerField(default=0),
        ),
    ]
